name: Set up OCaml
description: Set up an OCaml and opam environment and add to PATH
author: Sora Morimoto <sora@morimoto.io>
branding:
  icon: package
  color: orange
inputs:
  ocaml-version:
    description: The version of the OCaml compiler to initialise
    default: latest
  dune-cache:
    description: Specify whether to use the dune cache
    default: false
  opam-depext:
    description:
      Specify whether to query and install external dependencies of opam
      packages automatically
    default: true
  opam-disable-sandboxing:
    description:
      Specify whether to use a default configuration with sandboxing disabled
  opam-lint:
    description: Specify whether to run dune-lint
    default: false
  opam-local-packages:
    description: Packages to pass to opam pin and opam depext
    default: "*.opam"
  opam-pin:
    description:
      Specify whether to pin all opam local packages automatically that exist in
      the repository root
    default: true
  opam-repository:
    description: The URL of the repository to fetch packages from
  github-token:
    description:
      The token of GitHub to authenticate on behalf of the GitHub App installed
      on your repository
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
  post: dist/post/index.js
  post-if: success()
